const models = [
  {id:'yv-one',slug:'yardvest-one',name:'YardVest One',shortName:'One',status:'available',tagline:'Small footprint. Big potential.',shortDescription:'A compact, efficient home designed to maximize rental potential while fitting more properties.',longDescription:'Our most compact backyard home makes every square foot work harder, with a full kitchen, private bedroom and comfortable open living space.',bedrooms:1,bathrooms:1,squareFeet:545,width:"23′4″",depth:"23′4″",startingPrice:null,priceDisplay:null,coverImage:null,gallery:[],floorPlan:null,features:['1 private bedroom','Full bathroom','Full kitchen','In-suite laundry','Open living and dining','Efficient footprint'],finishPackages:['light','dark'],availableUpgrades:['flexible-living'],featured:true,sortOrder:1,visible:true},
  {id:'yv-two',slug:'yardvest-two',name:'YardVest Two',shortName:'Two',status:'available',tagline:'More room to make your own.',shortDescription:'More room and more rental potential, with two private bedrooms and generous shared living space.',longDescription:'A generous two-bedroom layout with an open kitchen, dining and living area, plus the practical storage and utility space that longer-term living demands.',bedrooms:2,bathrooms:1,squareFeet:809,width:null,depth:null,startingPrice:null,priceDisplay:null,coverImage:null,gallery:[],floorPlan:null,features:['2 private bedrooms','Full bathroom','Full kitchen','Pantry','Laundry and utility area','Open living and dining'],finishPackages:['light','dark'],availableUpgrades:[],featured:true,sortOrder:2,visible:true},
  {id:'yv-garage',slug:'yardvest-garage',name:'YardVest Garage',shortName:'Garage',status:'concept',tagline:'Keep the utility. Add the possibility.',shortDescription:'A future YardVest configuration for adding housing while preserving garage, parking or storage functionality.',longDescription:'A developing concept that brings home and garage functions together. Final configuration, dimensions and specifications will be shared as the design progresses.',bedrooms:null,bathrooms:null,squareFeet:null,width:null,depth:null,startingPrice:null,priceDisplay:null,coverImage:null,gallery:[],floorPlan:null,features:['Garage or storage function','Integrated living concept','Standardized YardVest approach'],finishPackages:[],availableUpgrades:[],featured:true,sortOrder:3,visible:true}
];
const finishPackages=[{id:'light',name:'Light',description:'A warm, bright material direction.',image:null,gallery:[],modelCompatibility:['yv-one','yv-two'],active:false},{id:'dark',name:'Dark',description:'A grounded, architectural material direction.',image:null,gallery:[],modelCompatibility:['yv-one','yv-two'],active:false}];
const upgrades=[{id:'flexible-living',name:'Flexible Living',category:'Interior',description:'An optional three-panel divider and integrated sofa/Murphy-bed solution for occasional private sleeping space.',price:null,modelCompatibility:['yv-one'],image:null,active:true,publiclyVisible:true},{id:'solar',name:'Solar',category:'Energy',price:null,modelCompatibility:['yv-one','yv-two'],active:false,publiclyVisible:false}];
const markets=[];
const faqs=[
 ['What is a YardVest home?','A YardVest is a thoughtfully designed, standardized home intended for unused backyard space. We focus on a small collection of practical designs rather than a custom-home process.'],
 ['Can I build one on my property?','Building rules vary by property and municipality. YardVest starts with your address so the applicable requirements and likely fit can be reviewed.'],
 ['How do I know which design will fit?','We look at your property, access, relevant rules and your goals, then recommend the YardVest model that may make the most sense.'],
 ['How much does a YardVest home cost?','Pricing depends on the model, property conditions, site work and location. We do not publish an unverified all-in price; a property review helps establish the right context.'],
 ['How long does construction take?','Timing varies with design documentation, permits, site conditions and builder availability. We provide a project-specific outline after an initial property review.'],
 ['Are permits included?','YardVest helps coordinate the process, including design documentation and permits. Exact scope is confirmed for each project.'],
 ['Can I finance the project?','Financing may be available depending on your circumstances and location. We can help identify potential paths, but approval rests with the finance provider.'],
 ['Are there government incentives?','Some jurisdictions offer incentives or financing for secondary housing. Programs and eligibility change, so qualification must be confirmed with the applicable provider.'],
 ['Can I rent the home?','Rental permissions and requirements vary locally. A YardVest is designed with practical rental use in mind, subject to applicable rules.'],
 ['Can I customize the home?','YardVest intentionally keeps choices focused. Select finishes and upgrades may be offered without turning the home into a custom design.'],
 ['What is YardVest Garage?','It is a design-in-development concept for homeowners who want added housing while retaining garage, parking or storage functionality.']
];
const main=document.querySelector('#main');
const analytics=(event,detail={})=>{window.yardVestEvents=window.yardVestEvents||[];window.yardVestEvents.push({event,detail,at:new Date().toISOString()});};
const art=(extra='')=>`<div class="architectural-scene ${extra}" role="img" aria-label="Conceptual architectural illustration of a modern shed-roof backyard home"><span class="scene-sun"></span><span class="scene-home"></span><span class="scene-deck"></span><span class="scene-tree"></span><span class="scene-caption">CONCEPTUAL VIEW · FINAL IMAGERY TO COME</span></div>`;
const card=m=>`<article class="home-card"><a href="#/homes/${m.slug}" aria-label="Explore ${m.name}"><div class="home-visual"><span class="status">${m.status==='concept'?'DESIGN IN DEVELOPMENT':`${m.bedrooms} BED · ${m.bathrooms} BATH`}</span><span class="mini-home"></span></div><div class="home-card-body"><h3>${m.name}</h3><div class="specs">${m.squareFeet?`APPROX. ${m.squareFeet} SQ. FT.`:'GARAGE + HOME'}</div><p>${m.shortDescription}</p><span class="text-link">${m.status==='concept'?'Explore the Concept':'Explore '+m.name} <span>↗</span></span></div></a></article>`;
const faqMarkup=(limit=faqs.length)=>`<div class="faq-list">${faqs.slice(0,limit).map(([q,a])=>`<div class="faq-item"><button class="faq-question" aria-expanded="false"><span>${q}</span><span>＋</span></button><div class="faq-answer"><p>${a}</p></div></div>`).join('')}</div>`;
function home(){return `<section class="hero"><div class="hero-copy"><span class="eyebrow">BACKYARD INCOME HOMES</span><h1>Your yard.<br><em>Your income.</em></h1><p>Turn unused backyard space into a beautifully designed home. YardVest makes it simple—from figuring out what you can build through permits, construction and getting the home ready to rent.</p><div class="hero-actions"><button class="button button-dark" data-property-check>Check My Property <span>↗</span></button><a class="button button-light" href="#/homes">Explore the Homes</a></div></div>${art()}</section>
<section class="section" id="homes"><div class="section-head"><div><span class="eyebrow">THREE HOMES. ONE SIMPLE PROCESS.</span><h2>Simple homes.<br>Designed beautifully.</h2></div><p>Choose from a small collection of thoughtful backyard homes. We’ll help determine which one is right for your property.</p></div><div class="homes-grid">${models.map(card).join('')}</div></section>
<section class="address-band"><div><h2>Start with your property.</h2><p>One address is enough to begin.</p></div><button class="button button-dark" data-property-check>Check My Property <span>↗</span></button></section>
<section class="section dark-section" id="process"><div class="section-head"><div><span class="eyebrow">HOW IT WORKS</span><h2>Backyard home.<br>Made simple.</h2></div><p>From the first property review to a finished home, YardVest keeps the process clear and coordinated.</p></div><div class="steps">${[['01','Check your property','Send us your address and we’ll start by determining what may be possible.'],['02','Choose your YardVest','We’ll recommend the model that makes sense for your property and goals.'],['03','We coordinate the build','YardVest helps coordinate design documentation, permits, site work and construction.'],['04','Make it work for you','Use your new home for rental income, family housing or additional space.']].map(s=>`<article class="step"><span>${s[0]}</span><h3>${s[1]}</h3><p>${s[2]}</p></article>`).join('')}</div></section>
<section class="split"><div class="asset-graphic"></div><div class="split-copy"><span class="eyebrow">THE OPPORTUNITY</span><h2>Put your backyard to work.</h2><p>A well-designed backyard home can turn unused land into a productive asset—creating potential rental income, useful housing and long-term property utility.</p><p>Every property and market is different. We start with fit before discussing project-specific numbers.</p><button class="button button-dark" data-property-check>Check My Property <span>↗</span></button></div></section>
<section class="section"><div class="incentive-panel"><div class="incentive-mark"><span>$</span></div><div class="incentive-copy"><span class="eyebrow">INCENTIVES & FINANCING</span><h3>There may be help available.</h3><p>Depending on your property, location and intended use, government incentives or financing programs may be available for secondary or backyard housing. YardVest can help identify programs that may apply.</p><p class="fine-print">Programs, eligibility and funding availability can change. Final eligibility is determined by the applicable government or funding provider.</p><a class="text-link" href="#/incentives">Explore incentives <span>↗</span></a></div></div></section>
<section class="section"><div class="section-head"><div><span class="eyebrow">WHY YARDVEST</span><h2>Designed for less friction.</h2></div></div><div class="why-grid">${[['01','Designed, not improvised','A small collection of homes designed to be built repeatedly.'],['02','Fewer decisions','We simplify the process instead of making every home a custom project.'],['03','One coordinated process','From early property review through construction.'],['04','Rental-minded layouts','Practical spaces designed around how people actually live and rent.']].map(x=>`<article class="why-item"><span>${x[0]}</span><h3>${x[1]}</h3><p>${x[2]}</p></article>`).join('')}</div></section>
<section class="partner-strip"><div><span class="eyebrow">BUILDERS & PARTNERS</span><h2>Build with YardVest.</h2><p>We’re developing a network of experienced partners who can deliver standardized YardVest homes with a consistent process.</p></div><a class="button button-light" href="#/builders">Become a Partner <span>↗</span></a></section>
<section class="section"><div class="section-head"><div><span class="eyebrow">COMMON QUESTIONS</span><h2>A clearer way to add a home.</h2></div><a class="text-link" href="#/faq">View all questions ↗</a></div>${faqMarkup(5)}</section>
<section class="final-cta"><span class="eyebrow">YOUR PROPERTY IS THE START</span><h2>What could your yard become?</h2><button class="button button-dark" data-property-check>Check My Property <span>↗</span></button></section>`}
function homesPage(){return `<section class="page-hero"><span class="eyebrow">THE YARDVEST COLLECTION</span><h1>A few great homes. Nothing extra.</h1><p>Thoughtful, repeatable designs for rental income, family housing and additional living space.</p></section><section class="section"><div class="homes-grid">${models.map(card).join('')}</div></section><section class="final-cta"><h2>Find the home that fits your yard.</h2><button class="button button-dark" data-property-check>Check My Property ↗</button></section>`}
function modelPage(m){analytics('model_viewed',{model:m.id});const specs=m.status==='concept'?'GARAGE + HOME · DESIGN IN DEVELOPMENT':`${m.bedrooms} BED · ${m.bathrooms} BATH · ~${m.squareFeet} SQ. FT.`;return `<section class="model-hero"><div class="model-title"><span class="eyebrow">${m.status==='concept'?'YARDVEST CONCEPT':'YARDVEST HOME'}</span><h1>${m.name}</h1><div class="model-meta"><span>${specs}</span></div><p>${m.longDescription}</p><button class="button button-dark" data-property-check data-model="${m.id}">${m.status==='concept'?'Ask About the Concept':'Check If It Fits My Property'} <span>↗</span></button></div><div class="model-art">${art()}</div></section><section class="section"><div class="section-head"><div><span class="eyebrow">AT A GLANCE</span><h2>${m.tagline}</h2></div><p>${m.shortDescription}</p></div><ul class="feature-list">${m.features.map(f=>`<li>${f}</li>`).join('')}</ul></section>${m.status!=='concept'?`<section class="section dark-section"><div class="section-head"><div><span class="eyebrow">FLOOR PLAN</span><h2>Every square foot,<br>considered.</h2></div><p>The original architectural plan can be placed here as an optimized image when supplied. Dimensions shown remain approximate.</p></div><div class="floorplan-shell"><div class="floorplan-placeholder"><svg viewBox="0 0 600 400" aria-label="Floor plan placeholder"><rect x="30" y="30" width="540" height="340"/><path d="M310 30v340M30 235h280M310 210h260M150 235v135M450 210v160M310 110h140M390 110v100"/><path d="M60 235v-35m90 35v-35m160 60h-35m175-60v-35m0-55h35"/></svg><p>ARCHITECTURAL PLAN ASSET PENDING</p></div></div></section>`:''}<section class="final-cta"><h2>Could ${m.name} fit your property?</h2><button class="button button-dark" data-property-check data-model="${m.id}">Start with your address ↗</button></section>`}
const pages={
 'how-it-works':()=>`<section class="page-hero"><span class="eyebrow">HOW IT WORKS</span><h1>One coordinated path to a backyard home.</h1><p>YardVest simplifies the decisions and helps move your project from early fit through delivery.</p></section><section class="section dark-section"><div class="steps">${[['01','Check your property','Share your address so we can start reviewing fit and applicable requirements.'],['02','Choose your YardVest','Select from a focused collection based on your property and goals.'],['03','Coordinate the build','We help coordinate documentation, permits, site work and construction.'],['04','Put it to use','Create rental housing, family space or added utility for your property.']].map(s=>`<article class="step"><span>${s[0]}</span><h3>${s[1]}</h3><p>${s[2]}</p></article>`).join('')}</div></section><section class="final-cta"><h2>Your address is step one.</h2><button class="button button-dark" data-property-check>Check My Property ↗</button></section>`,
 incentives:()=>`<section class="page-hero"><span class="eyebrow">INCENTIVES & FINANCING</span><h1>Support may be closer than you think.</h1><p>Some programs support secondary and backyard housing. We keep claims careful and help identify what may apply to your location and intended use.</p></section><article class="content-page"><h2>How we approach incentives</h2><p>Programs differ by jurisdiction and may involve grants, low-cost loans, fee relief or other support. YardVest can help identify relevant programs during property review, but does not determine eligibility.</p><h2>No universal promises</h2><p>Programs, eligibility and funding availability can change. Final eligibility is determined by the applicable government or funding provider.</p><button class="button button-dark" data-property-check>Check My Property ↗</button></article>`,
 faq:()=>`<section class="page-hero"><span class="eyebrow">FAQ</span><h1>Good questions deserve clear answers.</h1></section><section class="section">${faqMarkup()}</section>`,
 about:()=>`<section class="page-hero"><span class="eyebrow">ABOUT YARDVEST</span><h1>Better use of the space you already own.</h1></section><article class="content-page"><p>YardVest was created around a simple idea: many homeowners already own enough land to create another useful home.</p><p>By combining thoughtful standardized design with a simpler planning and construction process, YardVest aims to make backyard housing easier to understand, build and operate.</p><h2>Three homes. One simple process. Your property.</h2></article>`,
 builders:()=>`<section class="page-hero"><span class="eyebrow">BUILDERS & PARTNERS</span><h1>Build with YardVest.</h1><p>YardVest is developing a network of experienced builders and industry partners who can deliver standardized homes using a consistent process.</p></section><section class="content-page"><h2>Become a YardVest Partner</h2><p>We welcome interest from builders, general contractors, architects, engineers, financing specialists and property-management partners.</p><form class="partner-form" data-form="partner"><div class="field"><label>Name *</label><input name="name" required autocomplete="name"></div><div class="field"><label>Company *</label><input name="company" required autocomplete="organization"></div><div class="field"><label>Email *</label><input name="email" type="email" required autocomplete="email"></div><div class="field"><label>Phone</label><input name="phone" type="tel" autocomplete="tel"></div><div class="field"><label>Website</label><input name="website" type="url"></div><div class="field"><label>City / service area *</label><input name="serviceArea" required></div><div class="field full"><label>Partner type *</label><select name="partnerType" required><option value="">Choose one</option><option>Builder / general contractor</option><option>Architect / designer</option><option>Engineer</option><option>Financing partner</option><option>Real estate / property management</option><option>Other</option></select></div><div class="field full"><label>Brief message</label><textarea name="message" rows="4"></textarea></div><button class="button button-dark full" type="submit">Become a YardVest Partner ↗</button></form></section>`,
 contact:()=>`<section class="page-hero"><span class="eyebrow">CONTACT</span><h1>Start with your property—or simply say hello.</h1><p>For a property review, the fastest path is Check My Property. For everything else, email <a class="text-link" href="mailto:hello@yardvest.com">hello@yardvest.com</a>.</p></section><section class="final-cta"><h2>See what you may be able to build.</h2><button class="button button-dark" data-property-check>Check My Property ↗</button></section>`,
 privacy:()=>`<article class="content-page"><span class="eyebrow">LEGAL</span><h1>Privacy</h1><p>YardVest collects information you submit so we can respond to property and partner inquiries. We do not sell submitted personal information. This MVP stores a local browser copy when the server endpoint is unavailable; production deployment should configure secure server-side storage and retention.</p><h2>Information collected</h2><p>Contact details, property address, interests, notes, source page and relevant model interest.</p></article>`,
 terms:()=>`<article class="content-page"><span class="eyebrow">LEGAL</span><h1>Terms</h1><p>Website information is general and does not constitute legal, planning, financing or construction advice. Designs, dimensions and areas are approximate. Property eligibility, approvals, pricing, timelines, incentives and rental use require project-specific confirmation.</p></article>`
};
function bind(){document.querySelectorAll('[data-property-check]').forEach(b=>b.addEventListener('click',()=>openProperty(b.dataset.model)));document.querySelectorAll('.faq-question').forEach(b=>b.addEventListener('click',()=>{const item=b.closest('.faq-item');item.classList.toggle('open');b.setAttribute('aria-expanded',item.classList.contains('open'));b.lastElementChild.textContent=item.classList.contains('open')?'−':'＋'}));document.querySelectorAll('[data-form="partner"]').forEach(f=>f.addEventListener('submit',submitForm));}
function route(){const raw=location.hash.replace(/^#\/?/,'')||'';const parts=raw.split('/').filter(Boolean);let html;if(!parts.length)html=home();else if(parts[0]==='homes'&&parts[1]){const m=models.find(x=>x.slug===parts[1]);html=m?modelPage(m):homesPage()}else if(parts[0]==='homes')html=homesPage();else html=(pages[parts[0]]||(()=>`<article class="content-page"><h1>Page not found.</h1><p><a class="text-link" href="#/">Return home</a></p></article>`))();main.innerHTML=html;window.scrollTo(0,0);bind();document.querySelector('.mobile-nav').classList.remove('open');document.querySelector('.menu-toggle').setAttribute('aria-expanded','false');document.title=`${parts.length?(parts[1]?models.find(x=>x.slug===parts[1])?.name:parts[0].replaceAll('-',' '))+' — ':''}YardVest`;}
const dialog=document.querySelector('#property-dialog');function openProperty(model=''){document.querySelector('#model-interest').value=model;document.querySelector('#source-page').value=location.hash||'home';dialog.showModal();analytics('property_check_started',{model,source:location.hash||'home'});setTimeout(()=>document.querySelector('#property-address').focus(),50)}
document.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});document.querySelector('#property-form').addEventListener('submit',submitForm);
async function submitForm(e){e.preventDefault();const form=e.currentTarget;const type=form.dataset.form;const data=Object.fromEntries(new FormData(form));const lead={id:crypto.randomUUID?.()||`yv_${Date.now()}`,type,createdAt:new Date().toISOString(),status:'new',...data};let saved=false;try{const res=await fetch('api.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(lead)});const contentType=res.headers.get('content-type')||'';if(res.ok&&contentType.includes('application/json')){const result=await res.json();saved=result.ok===true}}catch{}if(!saved){const key='yardvest_leads';const leads=JSON.parse(localStorage.getItem(key)||'[]');leads.push(lead);localStorage.setItem(key,JSON.stringify(leads))}analytics(type==='property'?'property_check_submitted':'partner_form_submitted',{id:lead.id});if(type==='property'){dialog.innerHTML=`<div class="success-state"><span class="eyebrow">PROPERTY RECEIVED</span><h2>We’ve got your property.</h2><p>We’ll review it and help determine which YardVest home may be a fit.</p><button class="button button-dark" onclick="document.querySelector('#property-dialog').close()">Done</button></div>`}else{form.reset();showToast('Thanks—your partner inquiry has been received.')}}
function showToast(message){const t=document.querySelector('.toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3500)}
document.querySelector('.menu-toggle').addEventListener('click',e=>{const nav=document.querySelector('.mobile-nav');nav.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',nav.classList.contains('open'))});window.addEventListener('scroll',()=>document.querySelector('#site-header').classList.toggle('scrolled',scrollY>8));window.addEventListener('hashchange',route);document.querySelector('#year').textContent=new Date().getFullYear();route();
