create extension if not exists pgcrypto;

create type public.app_role as enum ('admin','advisor','customer','builder_partner');
create type public.project_stage as enum ('new_lead','property_review','advisor_contact','consultation_booked','consultation_complete','feasibility','reservation','proposal','contract_sent','contract_signed','deposit_due','deposit_paid','design_engineering','permits','pre_construction','construction','inspections','handover','complete','nurture','not_eligible','lost','cancelled');
create type public.review_result as enum ('yes','possible','no','requires_review');
create type public.record_status as enum ('draft','pending','active','complete','cancelled','expired');
create type public.payment_purpose as enum ('reservation','deposit','progress','other');

create table public.profiles (id uuid primary key references auth.users on delete cascade, role app_role not null default 'customer', first_name text, last_name text, phone text, created_at timestamptz not null default now());
create table public.contacts (id uuid primary key default gen_random_uuid(), user_id uuid references public.profiles, first_name text not null, last_name text not null, email text not null, phone text, created_at timestamptz not null default now(), unique(email));
create table public.properties (id uuid primary key default gen_random_uuid(), contact_id uuid not null references public.contacts, address_line text not null, city text, region text, postal_code text, country text, market_slug text, notes text, created_at timestamptz not null default now());
create table public.product_families (id uuid primary key default gen_random_uuid(), slug text unique not null, name text not null, status text not null, description text, sort_order int not null default 0, visible boolean not null default true, content jsonb not null default '{}');
create table public.product_styles (id uuid primary key default gen_random_uuid(), product_family_id uuid not null references public.product_families on delete cascade, slug text not null, name text not null, roof_form text, content jsonb not null default '{}', unique(product_family_id,slug));
create table public.plan_variants (id uuid primary key default gen_random_uuid(), product_family_id uuid not null references public.product_families on delete cascade, slug text not null, name text not null, bedrooms numeric, bathrooms numeric, footprint_width numeric, footprint_depth numeric, gross_area numeric, review_required boolean not null default false, content jsonb not null default '{}', unique(product_family_id,slug));
create table public.product_media (id uuid primary key default gen_random_uuid(), product_family_id uuid references public.product_families on delete cascade, style_id uuid references public.product_styles, plan_variant_id uuid references public.plan_variants, source_filename text not null, media_type text not null, storage_path text, metadata jsonb not null default '{}', sort_order int not null default 0, review_required boolean not null default true);
create table public.leads (id uuid primary key default gen_random_uuid(), contact_id uuid not null references public.contacts, property_id uuid not null references public.properties, source text, goal text, model_interest uuid references public.product_families, status record_status not null default 'active', created_at timestamptz not null default now());
create table public.projects (id uuid primary key default gen_random_uuid(), contact_id uuid not null references public.contacts, property_id uuid not null references public.properties, lead_id uuid unique references public.leads, stage project_stage not null default 'new_lead', advisor_id uuid references public.profiles, product_family_id uuid references public.product_families, style_id uuid references public.product_styles, plan_variant_id uuid references public.plan_variants, estimated_rent_low numeric, estimated_rent_high numeric, rent_disclaimer text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.property_reviews (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects on delete cascade, result review_result not null default 'requires_review', planning_notes text, access_notes text, servicing_notes text, approximate_allowable_size text, rent_low numeric, rent_high numeric, incentive_notes text, reviewer_id uuid references public.profiles, reviewed_at timestamptz, customer_summary text, created_at timestamptz not null default now());
create table public.consultations (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects on delete cascade, advisor_id uuid references public.profiles, starts_at timestamptz not null, ends_at timestamptz not null, timezone text not null, status record_status not null default 'pending', notes text, created_at timestamptz not null default now());
create table public.activities (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects on delete cascade, actor_id uuid references public.profiles, activity_type text not null, body text, metadata jsonb not null default '{}', created_at timestamptz not null default now());
create table public.tasks (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects on delete cascade, owner_id uuid references public.profiles, task_type text not null, title text not null, due_at timestamptz, status record_status not null default 'pending', created_at timestamptz not null default now());
create table public.reservations (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects on delete cascade, product_family_id uuid references public.product_families, amount numeric, currency text not null default 'CAD', terms text, refundable boolean, expires_at timestamptz, accepted_at timestamptz, status record_status not null default 'draft', created_at timestamptz not null default now());
create table public.proposals (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects on delete cascade, status record_status not null default 'draft', base_amount numeric, currency text not null default 'CAD', scope text, allowances text, exclusions text, schedule_notes text, incentive_notes text, expires_at timestamptz, created_at timestamptz not null default now());
create table public.proposal_items (id uuid primary key default gen_random_uuid(), proposal_id uuid not null references public.proposals on delete cascade, label text not null, description text, amount numeric, sort_order int not null default 0);
create table public.documents (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects on delete cascade, document_type text not null, title text not null, storage_path text, status record_status not null default 'draft', metadata jsonb not null default '{}', created_at timestamptz not null default now());
create table public.contracts (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects on delete cascade, document_id uuid references public.documents, provider text, provider_reference text, status record_status not null default 'draft', sent_at timestamptz, opened_at timestamptz, signed_at timestamptz, created_at timestamptz not null default now());
create table public.payments (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects on delete cascade, purpose payment_purpose not null, amount numeric not null, currency text not null default 'CAD', stripe_payment_id text unique, status text not null default 'pending', due_at timestamptz, paid_at timestamptz, created_at timestamptz not null default now());
create table public.pipeline_stage_history (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects on delete cascade, from_stage project_stage, to_stage project_stage not null, changed_by uuid references public.profiles, changed_at timestamptz not null default now());

alter table public.profiles enable row level security; alter table public.contacts enable row level security; alter table public.properties enable row level security; alter table public.leads enable row level security; alter table public.projects enable row level security; alter table public.property_reviews enable row level security; alter table public.consultations enable row level security; alter table public.activities enable row level security; alter table public.tasks enable row level security; alter table public.reservations enable row level security; alter table public.proposals enable row level security; alter table public.documents enable row level security; alter table public.contracts enable row level security; alter table public.payments enable row level security;

create policy "users read own profile" on public.profiles for select using (auth.uid() = id);
create policy "customers read own contact" on public.contacts for select using (user_id = auth.uid());
create policy "customers read own projects" on public.projects for select using (contact_id in (select id from public.contacts where user_id = auth.uid()));

-- Admin/advisor policies, anonymous lead intake, storage policies and Edge Functions
-- must be added with the configured production roles; do not grant broad anonymous table access.
